# Generated by Django 6.0 on 2025-12-04 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('address', models.TextField()),
                ('course', models.CharField(choices=[('Mathematics', 'Mathematics'), ('Science', 'Science'), ('History', 'History'), ('Art', 'Art'), ('Physical Education', 'Physical Education')], max_length=50)),
                ('year_of_study', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year'), (5, '5th Year')])),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('guardian_name', models.CharField(max_length=60)),
                ('guardian_contact', models.CharField(max_length=15)),
            ],
        ),
    ]
