# Generated by Django 6.0 on 2025-12-10 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_students_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile/')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student_app.students')),
            ],
        ),
    ]
